### ISSUE TITLE
插件结构改为package

### ISSUE THREAD

**Issue by zenas** [hanxu317317/city_pickers#109]
大致看了下源码，应该是没有任何需要原生模块交互的代码。为什么插件是一个plugin而不是package？纯flutter结构不应该作为plugin。

**Comment by hanxu317317** [comment]
这个问题之前就有小哥提出来过. 但是当时也是刚接触.   关于如何把plugin 转成package 有什么思路么. 需要修改什么嘛.

**Comment by hanxu317317** [comment]
#110  帮忙看一下. 这样改对不对.  查遍了百度也没有找到文档 .

**Comment by zenas** [comment]
不好意思，最近有点忙，看了下改动，应该没问题。
主要的逻辑就是yaml文里不要配置plugin，库自身的android、ios文件夹下都可以清除。其余的主要是一些生成配置文件或example相关的...

**Comment by hanxu317317** [comment]
好嘞~~感谢提出的意见. 我在找机子测试. 没问题会发一个大版本.
