### ISSUE TITLE
点中某城市，进去后，再返回，该城市所占的那一栏显示空白

### ISSUE THREAD

**Issue by xshengjing** [hanxu317317/city_pickers#112]
![2](https://user-images.githubusercontent.com/18089835/94105138-34dbd780-fe6b-11ea-9036-8ead771e1b6e.jpg)
![3](https://user-images.githubusercontent.com/18089835/94105142-373e3180-fe6b-11ea-92e7-3b4fe6bf22cc.jpg)

**Comment by hanxu317317** [comment]
ok, 收到了这个问题 .我会尽快处理.  有可能是activeColor: white了

**Comment by xshengjing** [comment]
> ok, 收到了这个问题 .我会尽快处理. 有可能是activeColor: white了

嗯嗯，方便加你微信嘛，我刚使用flutter没多久，经验不足，向你学习下
