### ISSUE TITLE
点击返回退出时，报错

### ISSUE THREAD

**Issue by xshengjing** [hanxu317317/city_pickers#113]
![1](https://user-images.githubusercontent.com/18089835/94105210-618fef00-fe6b-11ea-9e3b-69c0b59665c5.jpg)

**Comment by hanxu317317** [comment]
收到该问题. 我这边会周末前发版.

**Comment by xshengjing** [comment]
> 收到该问题. 我这边会周末前发版.

**Comment by xshengjing** [comment]
> 收到该问题. 我这边会周末前发版.


> > 收到该问题. 我这边会周末前发版.

嗯嗯，辛苦
