### ISSUE TITLE
点击速度过快会闪退

### ISSUE THREAD

**Issue by woshihfh0123** [hanxu317317/city_pickers#121]
如果以很快的速度连续点击省市县列表（大概一秒钟内点完省市县），选择区县之后会闪退，报错内容：
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building FullPage(dirty, state: _FullPageState#a856a):
The getter 'code' was called on null.
Receiver: null
Tried calling: code

The relevant error-causing widget was: 
  FlutterEasyLoading file:///D:/workspace/91Chedai_GIT_NEW/lib/main.dart:137:22
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _FullPageState._getSelectedId (package:city_pickers/src/full_page/full_page.dart:224:31)
#2      _FullPageState.build (package:city_pickers/src/full_page/full_page.dart:320:29)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
[ +167 ms] I/flutter (31682): asd
[        ] E/flutter (31682): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 176 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
[        ] E/flutter (31682): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] E/flutter (31682): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] E/flutter (31682): #2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:176:12)
[        ] E/flutter (31682): #3      _FullPageState._onItemSelect.<anonymous closure> (package:city_pickers/src/full_page/full_page.dart:283:30)
[        ] E/flutter (31682): #4      setTimeout.<anonymous closure> (package:city_pickers/src/util.dart:57:13)
[        ] E/flutter (31682): #5      _rootRun (dart:async/zone.dart:1182:47)
[        ] E/flutter (31682): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter (31682): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] E/flutter (31682): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] E/flutter (31682): #9      _rootRun (dart:async/zone.dart:1190:13)
[        ] E/flutter (31682): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter (31682): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
[        ] E/flutter (31682): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] E/flutter (31682): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
[        ] E/flutter (31682): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
[        ] E/flutter (31682): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[        ] E/flutter (31682): 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════

**Comment by hanxu317317** [comment]
这个问题. 貌似是稳定复现的. ~~ coding

**Comment by hanxu317317** [comment]
Navigator.of(context).pop. 这个方法在那一瞬间. 调用过多. 超过了堆栈. 黑屏了.
