### ISSUE TITLE
能否在showCityPicker左右上面显示圆角？

### ISSUE THREAD

**Issue by HelmsManLi** [hanxu317317/city_pickers#122]

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/121635714-4b899380-cab9-11eb-8023-a1cc4500ea8f.png)

这里变成圆角?

**Comment by wl386123298** [comment]
@hanxu317317 是的，希望有参数可以设置圆角

**Comment by hanxu317317** [comment]
拉取develop分支. 看一下效果. 是否是你想要的? 没问题.我这边测试测试. 就准备发布掉了.
![image](https://user-images.githubusercontent.com/8518989/132698788-4101c6ff-5690-4aae-bdd0-6aa73ca10308.png)
![image](https://user-images.githubusercontent.com/8518989/132698813-efe8d393-67c5-4726-86c9-4bc75a4b572e.png)
