### ISSUE TITLE
flutter 2.0 编译错误

### ISSUE THREAD

**Issue by coscx** [hanxu317317/city_pickers#123]
Scaffold 需要把 resizeToAvoidBottomPadding: false注释掉
![image](https://user-images.githubusercontent.com/73681626/110199831-54087780-7e95-11eb-9afd-4cb517c6db3d.png)

**Comment by longfit** [comment]
請問以可自行修正？

**Comment by phonegap100** [comment]
参考：http://bbs.itying.com/topic/60acaa370949250f402ff2e5

**Comment by hanxu317317** [comment]
#128
