### ISSUE TITLE
WEB 不支持, Windows 也不支持.

### ISSUE THREAD

**Issue by bulanni00** [hanxu317317/city_pickers#124]
/E:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/city_pickers-0.2.0/lib/src/cities_selector/cities_selector.dart:415:9: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
        resizeToAvoidBottomPadding: false,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/E:/SDK/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^

Failed to compile application.

**Comment by hanxu317317** [comment]
现在flutter-web 流行起来了么?

**Comment by hanxu317317** [comment]
已经修复并支持~~~
