### ISSUE TITLE
什么时候能支持nullsafety版本

### ISSUE THREAD

**Issue by irooty** [hanxu317317/city_pickers#130]
如题

**Comment by phonegap100** [comment]
参考：http://bbs.itying.com/topic/60acaa370949250f402ff2e5

**Comment by yangchunboy** [comment]
> 参考：http://bbs.itying.com/topic/60acaa370949250f402ff2e5

你那个git还是有问题，package:lpinyin也没有升到nullsafety版本
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:city_pickers
     - package:lpinyin

    For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by yangchunboy** [comment]
> 参考：http://bbs.itying.com/topic/60acaa370949250f402ff2e5

Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN),这是我的flutter版本

**Comment by hanxu317317** [comment]
#128

**Comment by hanxu317317** [comment]
正苦逼兮兮的改动中. 1.0版本.暂时是beta版本.

**Comment by hanxu317317** [comment]
最新1.0.1 中已经修复发布, 并且解决unsafe的问题.
