### ISSUE TITLE
升级到最新的版本city_pickers: 1.0.0还是提示有null safety

### ISSUE THREAD

**Issue by yangchunboy** [hanxu317317/city_pickers#131]
我的flutter版本是Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)

 7 warnings generated.
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:city_pickers
     - package:lpinyin

    For solutions, see https://dart.dev/go/unsound-null-safety

    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by hanxu317317** [comment]
正常处理剩下的.代码.  这次更新要改吐了.

**Comment by hanxu317317** [comment]
最新1.0.1 中已经修复发布, 并且解决unsafe的问题.
