### ISSUE TITLE
可以修改 APPbar 吗？   想在顶部导航栏右侧增加个按钮

### ISSUE THREAD

**Issue by 18518278831** [hanxu317317/city_pickers#136]
showCitiesSelector    showCitiesSelector   可以修改 APPbar 吗？   想在顶部导航栏右侧增加个按钮

**Comment by hanxu317317** [comment]
let me see see~~~

**Comment by 18518278831** [comment]
嗯嗯，麻烦您了。希望可以增加APPbar 按钮

**Comment by hanxu317317** [comment]
@18518278831 拉取develop分支. 看一下效果. 是否是你想要的? 没问题.我这边测试测试. 就准备发布掉了.

**Comment by hanxu317317** [comment]
构建了一个新的属性: appBarBuilder
![image](https://user-images.githubusercontent.com/8518989/132698877-4543ca6f-dccc-424e-8e2b-485abadb9a5c.png)

**Comment by 18518278831** [comment]
好的多谢您，效率真高呀

**Comment by 18518278831** [comment]
您大概什么时候发布新版本呢？

**Comment by hanxu317317** [comment]
9.13号本周内.

**Comment by hanxu317317** [comment]
1.1.0 已经发布上线.
