### ISSUE TITLE
自定义数据初始化失败

### ISSUE THREAD

**Issue by welnstar** [hanxu317317/city_pickers#14]
在CityTree中的_getProvinceByCode方法中 不应该使用citiesData常量 应该使用CityTree初始化时候的metaInfo，不然搜索的还是原来的cityCode而不是用户设置的数据

**Comment by hanxu317317** [comment]
cityTree那个是默认值.  已经在 0.1.12 中修复.

**Comment by welnstar** [comment]
> cityTree那个是默认值. 已经在 0.1.12 中修复.

不好意思，可能我当时没说清楚，原来其实是支持自定义数据的，只是在lib\modal\base_city.dart文件中第64、67行的查找中把 自定义数据又改回了默认数据，当数据中citycode和默认数据不一致的时候会出现错误

其中 64行  List<String> keys = citiesData.keys.toList();
应该为  List<String> keys = metaInfo.keys.toList();
67行 Map<String, dynamic> child = citiesData[key];
应该为 Map<String, dynamic> child = metaInfo[key];

**Comment by hanxu317317** [comment]
明白了. 这块疏忽了.  小哥看的很细心. 最近一边支持flutter go .一边维护这边. 有点忙. 马上修复~~
