### ISSUE TITLE
#bug 。 选择省份后，立马快速滑动城市，报错并且卡死。

### ISSUE THREAD

**Issue by Junesui** [hanxu317317/city_pickers#146]
`dart`

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FixedExtentScrollController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 2736 pos 12: '!_debugDisposed': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject.markNeedsSemanticsUpdate (package:flutter/src/rendering/object.dart:2736:12)
#3      _RenderCupertinoPickerSemantics._handleScrollUpdate (package:flutter/src/cupertino/picker.dart:480:5)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:324:24)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:324:24)
#6      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:969:11)
#7      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:278:9)
#8      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#9      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
#10     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
#11     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:651:12)
#12     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
#13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#14     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
#15     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#31     _invoke1 (dart:ui/hooks.dart:170:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _AssertionError and dart:async)
The FixedExtentScrollController sending notification was: FixedExtentScrollController#7cc73(one client, offset 13.1)
====================================================================================================

`dart`

**Comment by hanxu317317** [comment]
使用的是什么版本的pickers/

**Comment by Junesui** [comment]
> 
最新版。
city_pickers: ^1.1.2

除此之外，还有个问题，滑动省份时候城市还没变化，快速滑动城市的话还是上个省份的城市

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/182357630-75154e89-2412-440e-bcc6-87e39197ecec.png)


哪个picker有问题? web版本能复现 么?

**Comment by hanxu317317** [comment]
https://pmbee.alicdn.com/flutter/city_pickers/index.html#/

**Comment by Junesui** [comment]
ios选择器。
web数据太少，再现不出来。 我只用了省和城市两个节点。

**Comment by Junesui** [comment]
![image](https://user-images.githubusercontent.com/53398033/182358154-66a902af-836a-4571-8dd0-9806195928e0.png)

**Comment by hanxu317317** [comment]
sanfan.hx@alibaba-inc.com

用手机录个屏幕. 发到我邮箱~~~我本地再试试. 这样定位最快.

**Comment by Junesui** [comment]
已发送。两封，两个问题。 感谢开源。

**Comment by hanxu317317** [comment]
let me see ~~

**Comment by hanxu317317** [comment]
1.1.3 更新一下版本. 应该是解决问题了.  期待你的回复
