### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by kaiminglb** [hanxu317317/city_pickers#168]
Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
local Flutter  3.10.1

**Comment by ipcjs** [comment]
The issue has be fix on master branch.
@hanxu317317 can you release new version to pub.dev?

**Comment by kaiminglb** [comment]
expect

**Comment by hanxu317317** [comment]
thk~~

**Comment by hanxu317317** [comment]
v1.3.0 published
