### ISSUE TITLE
选择 广东-深圳 时，区的数据没有同步修改

### ISSUE THREAD

**Issue by bg7lgb** [hanxu317317/city_pickers#2]
{provinceName: 广东省, provinceId: 440000, cityName: 深圳市, cityId: 440300, areaName: 荔湾区, areaId: 440103}

**Comment by hanxu317317** [comment]
![issue](https://user-images.githubusercontent.com/8518989/53156961-7a834f00-35fb-11e9-8b6f-a874992cc7e4.gif)
这个的复现场景, 是什么样的?

**Comment by bg7lgb** [comment]
这样重现，选任意一个省->市，比如广东，第一个就是广州，荔湾。然后选深圳，数据变动了，但返回的数据中区还是荔湾

**Comment by bg7lgb** [comment]
界面上已变化 ，返回的数据 没变，result 中的数据。{provinceName: 广东省, provinceId: 440000, cityName: 韶关市, cityId: 440200, areaName: 荔湾区, areaId: 440103}

**Comment by hanxu317317** [comment]
已发布至0.1.8.
