### ISSUE TITLE
pickerItem 问题 

### ISSUE THREAD

**Issue by rcj60560** [hanxu317317/city_pickers#22]
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "city picker",
      home: Scaffold(
        appBar: AppBar(
          title: Text("city picker"),
        ),
        body: new Column(
          children: <Widget>[
            new Container(
              child: _buildShowTypes(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildShowTypes() {
    return Picker(
      target: new Container(
        color: Colors.red,
        child: Text(
          name,
          style: TextStyle(fontSize: 20),
        ),
      ),
      onConfirm: (PickerItem item) {
        setState(() {
          name = item.name;
        });
      },
      items: [
        PickerItem(name: '男',value: null),
        PickerItem(name: '女',value: null),
      ],
    );
  }

@hanxu317317 你好这个是我代码，应该有个默认值 比方说我点击一个按钮 底部弹出2个选项 男 女，然后我点击屏幕其他地方消失，如果用户没有滚动选择 点击确定，并不能选中想要的值，比方说 男女 现在显示是女，然后点击弹出底部选择 ，直接点击确定，没有滚动，就不能选中男了。。。不知道我描述您能听懂吗

**Comment by hanxu317317** [comment]
这个问题. 之前我制作组件的时候,也困扰了我.有二种方式去处理
1. 增加一个 请选择的item, value= -1, 当点击确定的时候, 进行判断. 
2. 在组件内部直接初始化的时候. 用items[0]的值, 做为被选中的数据.

不知道能否解决你的问题.

**Comment by rcj60560** [comment]
关键我 我能大概知道什么意思 不晓得怎么下手，，，刚看flutter没几天 
so。。。。。。。。。。。。。。。

**Comment by hanxu317317** [comment]
参考一下:https://github.com/hanxu317317/city_pickers/blob/develop/example/lib/src/picker.dart

```
 void initState() {
    // TODO: implement initState
    result = widget.items[0];
    super.initState();
  }
```

这里边的办法就是上面说的第二种.
