### ISSUE TITLE
自定义数据源问题

### ISSUE THREAD

**Issue by mitty1987** [hanxu317317/city_pickers#24]
如果省市数据源是自定义的，但是在CityTree里仍然是用的自带数据源provincesData，如果id不匹配就会报错，报错代码行，
PinyinHelper.getFirstWordPinyin(name).substring(0, 1);
所以能否在CityTree里也传入自定义的身份数据源？

**Comment by hanxu317317** [comment]
@mitty1987 您用的哪个函数的方法. 我这边测试一下

**Comment by hanxu317317** [comment]
```
initTree(int provinceId) {
    String _cacheKey = provinceId.toString();
    if (_cache.has(_cacheKey)) {
      return tree = _cache.get(_cacheKey);
    }

    String name = provincesData[provinceId.toString()];
    String letter = PinyinHelper.getFirstWordPinyin(name).substring(0, 1);
    var root =
        new Point(code: provinceId, letter: letter, child: [], name: name);
    tree = _buildTree(root, metaInfo[provinceId.toString()], metaInfo);
    _cache.set(_cacheKey, tree);
    return tree;
  }
```
我看了一下. 是这个函数的调用,可是省的code码. 是通用的.  我直接使用了我本地的json数据. 不明白您的数据源. 是否正确 .

**Comment by mitty1987** [comment]
我自己的数据源是类似这样的 {"1", "上海"}...这样 String name = provincesData[provinceId.toString()];这句在执行的时候回去查找1的id，provincesData里是没有1这条数据的，所以getFirstWordPinyin(name)里报了个空
Result tempResult = await CityPickers.showCityPicker(
                                            showType: ShowType.pc,
                                            context: context,
                                            provincesData: provincesData,
                                            locationCode: "1",
                                            citiesData: citiesData);
这个是我的代码

**Comment by mitty1987** [comment]
我这边因为情况特殊，地址里是不能带市或者省，数据是从网站上的获取的，然后解析成数据源，但是id我没办法去逐个匹配，所以就自定义了数据。

**Comment by hanxu317317** [comment]
好的. 我这这边尽快适配一下这种,非标准数据源的问题.但是从长远的角度考虑. 地区信息尽量使用标准的code码.

**Comment by mitty1987** [comment]
好的，真是非常感谢。

**Comment by hanxu317317** [comment]
问题已经解决 version => 0.1.15
@mitty1987

**Comment by hanxu317317** [comment]
@mitty1987 期待你的反馈.
