### ISSUE TITLE
字体大小是不是可以自己调整

### ISSUE THREAD

**Issue by xiongwenzhi** [hanxu317317/city_pickers#29]
字体大小是不是可以自己调整，现在的字体有点大，有的显示不全。

**Comment by hanxu317317** [comment]
哪个方法的字体?

**Comment by wyhstar** [comment]
主题可以设置字体大小吗？没找到方法，我修改了源码，不知道后期会不会出问题

**Comment by hanxu317317** [comment]
@wyhstar 当时忘记考虑这块了. 最近正在整理这块.  觉得现在的字体小了还是大了?

**Comment by wyhstar** [comment]
很大，如果是个可配置的最好不过了 辛苦

在 2019-06-25 18:10:30，"hanxu317317" <notifications@github.com> 写道：


@wyhstar 当时忘记考虑这块了. 最近正在整理这块. 觉得现在的字体小了还是大了?

**Comment by hanxu317317** [comment]
@wyhstar 


version: 0.1.18

```
await CityPickers.showCityPicker(
  context: context,
 ...
  cancelWidget: Text('cancle', style: TextStyle())
  confirmWidget: Text('confirm', style: TextStyle())
  );
```
可以自行更改在不同主题色的按钮样式. 避免被 隐身的情况

**Comment by hanxu317317** [comment]
其他二个控制字体的正在加入中.

**Comment by allbluesea** [comment]
CityPickers.showCityPicker 这个方法里 item 的 字体大小 给个入口吧 不想去源码里修改

**Comment by hanxu317317** [comment]
@firebrk 这个在 #43 中已经解决了. 
属性 **itemBuilder**

**Comment by allbluesea** [comment]
@hanxu317317 ok
