### ISSUE TITLE
自己数据会报错?

### ISSUE THREAD

**Issue by sm9i** [hanxu317317/city_pickers#30]
传递自己数据会报错  The getter child wa called on null

**Comment by sm9i** [comment]
Result result = await CityPickers.showCityPicker(
        context: context,
        locationCode: "0",
        showType: ShowType.p,
        provincesData: timeData);



const Map<String, String> timeData = {
  "0": "30天",
  "1": "90天",
};

**Comment by sm9i** [comment]
不自定义 数据就不会报错，自定义就会报错。

**Comment by sm9i** [comment]
然后修改 timeData 的key     如果key 和你 写死的 provincesData 数据 不对应的话 就会 报错 ，
比如 898844  就会报错的， 反之 不报错 但是 不会返回  自定义数据的value 还是返回写死数据的 。求解决。  但是展示的 还是我自定的数据，返回的确实 作者写死的，，可能是我缓存的原因，，我是个小白，求解惑

**Comment by sm9i** [comment]
第一个 没问题 再 第二个选择就会报错的

**Comment by hanxu317317** [comment]
如果你配置了自定少的provinceData, 是不是也要配置一下. citiesData.

**Comment by hanxu317317** [comment]
或者说. 你的provinceData. 如果是标准的数据源, 可以不用管citiesData,
但是你用123456这种做配置. 拿不到下一层的数据就会报错. 
我这边做做兼容处理这个错误, 但是这个用法是不正确的.

**Comment by sm9i** [comment]
不行。。key 必须你是里面存在的 不然报错，。。。

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/56876849-d693a500-6a7c-11e9-96b7-8155e6693d58.png)

这是我demo中的demo示例.

**Comment by sm9i** [comment]
不是这个的，，是自定义数据会报错。。  一个可能不报错 多个 选择就报错了。

**Comment by hanxu317317** [comment]
把你的自定义数据. 完整的发出来. 我看一下

**Comment by sm9i** [comment]
const Map<String, String> timeData = {
  "110000": "30天",
  "120000": "90天",
};
const Map<String, String> marryData = {
  "130000": "未婚",
  "140000": "已婚",
  "150000": "离异",
  "210000": "丧偶",
};
const Map<String, String> eduData = {
  "320000": "高中以下",
  "330000": "高中",
  "340000": "中专",
  "350000": "大专",
  "360000": "本科及以上",
};
const Map<String, String> jobData = {
  "370000": "自由职业者",
  "410000": "上班族",
  "420000": "个体户",
  "430000": "其他",
};

///
/// 申请额度
///
const Map<String, String> priceData = {
  "440000": "3000",
  "450000": "5000",
  "460000": "8000",
  "500000": "10000",
  "510000": "15000",
  "520000": "20000",
};


不会发图片，，那个 现在 其他正常 然后选  时间的话 30天 直接返回北京。  90天正常，，我也不知什么鬼。。

**Comment by sm9i** [comment]
搜嘎，，我知道了。。使用了默认数据之后 就不能使用自定义数据了。如果使用自定义数据的话  id 不能一样    就算不在同一个选择器  也会默认选择  默认数据的    必须改id 为不一样的 才可以。。。

**Comment by sm9i** [comment]
const Map<String, String> timeData = {
  "10086": "30天",
  "10087": "90天",
};
const Map<String, String> marryData = {
  "10088": "未婚",
  "10089": "已婚",
  "10090": "离异",
  "10091": "丧偶",
};
const Map<String, String> eduData = {
  "10092": "高中以下",
  "10093": "高中",
  "10094": "中专",
  "10095": "大专",
  "10096": "本科及以上",
};
const Map<String, String> jobData = {
  "10097": "自由职业者",
  "10098": "上班族",
  "10099": "个体户",
  "10100": "其他",
};  现在就报错 改了 key 之后

**Comment by hanxu317317** [comment]
我现在没明白...你这个使用是怎么用的,感觉你是把这个组件当成单选的picker组件了么?

**Comment by hanxu317317** [comment]
方便的话. 可以把你的代码git地址放出来. 我本地运行一下试试

**Comment by sm9i** [comment]
不方便。。。。抱歉啊。。但是解决了。所有都按照你的id 来的。

**Comment by hanxu317317** [comment]
你不是解决

**Comment by hanxu317317** [comment]
@sm9i 问题解决了么? 如果可以关issue了

**Comment by sm9i** [comment]
结局不了。可能是我的问题吧，谢谢，我换插件了
