### ISSUE TITLE
不支持自动设定主题了么？我这不设置主题看不到确定和取消按钮。

### ISSUE THREAD

**Issue by hugoGuo** [hanxu317317/city_pickers#34]

**Comment by hanxu317317** [comment]
是按Example中的使用方法做的么. 我记得这个组件不能直接在 MaterialApp的Widget中直接去用. 需要在他的子组件中用.

**Comment by StarAndRainbow** [comment]
![image](https://user-images.githubusercontent.com/28133038/58524966-93a02b00-81fc-11e9-88ef-e78fb38c7a33.png)
我也修改不了，因为我的主题用了白色，所以看不到按钮颜色emmm，然后我去找这个插件的代码，直接修改了颜色。重装app即可生效

**Comment by hanxu317317** [comment]
@StarAndRainbow 像这种情况 . 我们可以在使用组件的时候. 在外层new Theme.
然后把primaryColor改写成你想要的颜色.也是可以的.

**Comment by hanxu317317** [comment]
@StarAndRainbow 

version: 0.1.18

```
await CityPickers.showCityPicker(
  context: context,
 ...
  cancelWidget: Text('cancle', style: TextStyle())
  confirmWidget: Text('confirm', style: TextStyle())
  );
```
可以自行更改在不同主题色的按钮样式. 避免被 隐身的情况
