### ISSUE TITLE
白色主题全屏设置的情况下已选择的城市item 字体颜色也为白色，导致不可见

### ISSUE THREAD

**Issue by hufu4635** [hanxu317317/city_pickers#40]
白色主题下，选中的item上的字体变为白色，导致不可见

**Comment by hanxu317317** [comment]
@hufu4635 正在修复中.

**Comment by hanxu317317** [comment]
@hufu4635 白色主题是?  ThemeData.light()?

**Comment by hufu4635** [comment]
不是的，是` primaryColor: Colors.white,`    采用的`'ThemeData.of(context)' `模式

**Comment by hanxu317317** [comment]
好的.明白了.  因为现在弹出层的背景色是白色的. 按钮的颜色使用的primarycolor, 所以导致这个问题

**Comment by hanxu317317** [comment]
@hufu4635 

version: 0.1.18

```
await CityPickers.showCityPicker(
  context: context,
 ...
  cancelWidget: Text('cancle', style: TextStyle())
  confirmWidget: Text('confirm', style: TextStyle())
  );
```
可以自行更改在不同主题色的按钮样式. 避免被 隐身的情况

**Comment by hufu4635** [comment]
我是采用showFullPageCityPicker 进行调用的  更新版本后进入选择器页面，对应已选的城市依然是白色的，不可用。 
另外通过该方式调用进入选择器页面后，点击返回键(或页面左上角返回按钮)不支持退出选择器页面。

Android环境

**Comment by hanxu317317** [comment]
你可以试着拉一下源代码跑一下.Example. 返回键我这边测试是正常的android & ios. 你那边有报错信息么?

**Comment by hanxu317317** [comment]
@hufu4635

**Comment by hufu4635** [comment]
> @hufu4635
example中
main.dart  修改primaryColor: Color(0xFFC91B3A)  为primaryColor: Colors.white
页面中选择省市县三级全屏联动->主题选择为ThemeData.of(context) ->点击展示city picker->进入到选择城市页面就会发现默认选择的城市因为白色主题导致item不可见问题
android平台 master分支代码

example 中点击返回键不会出现不支持退出选择页面。

**Comment by hanxu317317** [comment]
您可以参考一下example的用法.  或者您把你的demo扔出来. 我帮您定位一下问题.

**Comment by hufu4635** [comment]
> 您可以参考一下example的用法. 或者您把你的demo扔出来. 我帮您定位一下问题.

**白色主题不可见那个问题example也会出现**
**修改example的  main.dart** 中修改primaryColor: Color(0xFFC91B3A) 为primaryColor: Colors.white
页面中选择省市县三级全屏联动->主题选择为ThemeData.of(context) ->点击展示city picker->进入到选择城市页面**就会发现item不可见问题**

**Comment by hanxu317317** [comment]
@hufu4635 item不可见的问题. 我正在解决. 我说的是: "点击返回无效的问题"

**Comment by hufu4635** [comment]
好的 有时间的时候 我试试看能不能复现 判断下是哪里的问题

**Comment by hanxu317317** [comment]
白色主题, 数据看不到的问题.已修复@hufu
