### ISSUE TITLE
滚动文字字体大小颜色等

### ISSUE THREAD

**Issue by shanzhenghan** [hanxu317317/city_pickers#43]
现在的版本0.1.19  还不能自定义滚轮文字的字体大小和颜色 是吗

**Comment by hanxu317317** [comment]
```
// type 1
Result result = await CityPickers.showCityPicker(
  context: context,
);
// type 2
Result result2 = await CityPickers.showFullPageCityPicker(
  context: context,
);
// type 3
Result result2 = await CityPickers.showCitiesSelector(
  context: context,
);
```


您说的是哪个方法的滚轮颜色, 是type 3么?



@shanzhenghan

**Comment by shanzhenghan** [comment]
> showCityPicker



> ```
> // type 1
> Result result = await CityPickers.showCityPicker(
>   context: context,
> );
> // type 2
> Result result2 = await CityPickers.showFullPageCityPicker(
>   context: context,
> );
> // type 3
> Result result2 = await CityPickers.showCitiesSelector(
>   context: context,
> );
> ```
> 
> 您说的是哪个方法的滚轮颜色, 是type 3么?
type1   IOS风格底部弹窗 滚轮的那种

**Comment by hanxu317317** [comment]
@shanzhenghan 
![image](https://user-images.githubusercontent.com/8518989/60637488-37f53d00-9e4d-11e9-96a5-e5a6e421d53b.png)


![image](https://user-images.githubusercontent.com/8518989/60637505-45aac280-9e4d-11e9-8460-8676ea6c7190.png)


```
showCityPicker(
....
                 itemExtent: 50,
                  itemBuilder: (item, list, index) {
                    return Center(
                        child: Text(item, maxLines: 1, style: TextStyle(fontSize: 55)));
                  }
)
```

**Comment by shanzhenghan** [comment]
> @shanzhenghan
> ![image](https://user-images.githubusercontent.com/8518989/60637488-37f53d00-9e4d-11e9-96a5-e5a6e421d53b.png)
> 
> ![image](https://user-images.githubusercontent.com/8518989/60637505-45aac280-9e4d-11e9-8460-8676ea6c7190.png)
> 
> ```
> showCityPicker(
> ....
>                  itemExtent: 50,
>                   itemBuilder: (item, list, index) {
>                     return Center(
>                         child: Text(item, maxLines: 1, style: TextStyle(fontSize: 55)));
>                   }
> )
> ```

哈哈好的 原来这样 感谢  对了 还有个问题 滚轮省分的排序是按照字母abcde....排序的  有方法按照map中的省份数据进行排序显示吗

**Comment by hanxu317317** [comment]
这个暂时还没办法实现. 基本上产品角度都是按字母排序的.  论省份来的话. 这个其实也行. 就是一行判断的事,

**Comment by shanzhenghan** [comment]
> 这个暂时还没办法实现. 基本上产品角度都是按字母排序的. 论省份来的话. 这个其实也行. 就是一行判断的事,

嗯嗯  后续版本能加上吗 辛苦了  哈哈  感觉一打开滚轮最顶上就显示 澳门特别行政..个人感觉有点突兀 哈哈

**Comment by hanxu317317** [comment]
好好的. 可以的. 下一个小版本加上.

**Comment by shanzhenghan** [comment]
> 好好的. 可以的. 下一个小版本加上.

OK  辛苦 感谢

**Comment by hanxu317317** [comment]
@shanzhenghan 
v0.1.20

```
await CityPickers.showCityPicker(
                  context: context,
                  ...
                  isSort: false
);
```

已经加上去了.

**Comment by shanzhenghan** [comment]
> @shanzhenghan
> v0.1.20
> 
> ```
> await CityPickers.showCityPicker(
>                   context: context,
>                   ...
>                   isSort: isSort
> );
> ```
> 
> 已经加上去了.

给力啊 大佬 哈哈 好的 我去增加一下

**Comment by hanxu317317** [comment]
这个属性, 暂时还没暴露出去. 因为city 与 area现在还没有做排序.  只对省份进行了操作.

**Comment by shanzhenghan** [comment]
> 这个属性, 暂时还没暴露出去. 因为city 与 area现在还没有做排序. 只对省份进行了操作.

OK了 效果达到了  哈哈
