### ISSUE TITLE
如何自己设置数据，显示单级，双极，多级滚动呢

### ISSUE THREAD

**Issue by jp1017** [hanxu317317/city_pickers#45]

**Comment by hanxu317317** [comment]
@jp1017  亲. 您可以拉下代码跑起来Example中的代码看一下. 有基本示例的. 只显示省, 省+城, 城+地区的用法 .

因为上班时间业务压力大. web版正在梳理中.

**Comment by jp1017** [comment]
刚跑了，看到了，哈哈哈，感谢

**Comment by hanxu317317** [comment]
欢迎提bug. 文档框架还在写. 自己要做一个东西. 太难了.
