### ISSUE TITLE
省市区数据的问题。

### ISSUE THREAD

**Issue by wyhstar** [hanxu317317/city_pickers#47]
作者大佬什么时候能更新一下数据源呢，很多区都没有的

**Comment by hanxu317317** [comment]
@wyhstar 这个数据最近变化那么多嘛. 那我这二天更新一下

**Comment by wyhstar** [comment]
@hanxu317317   http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/  我在这个链接看的 只看了苏州的 就少了一个工业园区呢  老哥辛苦

**Comment by hanxu317317** [comment]
@wyhstar 哈哈好的.  加班也要弄出来~~

**Comment by wyhstar** [comment]
@hanxu317317  手动点赞

**Comment by hanxu317317** [comment]
@wyhstar 
version: 0.1.22
https://pub.dev/packages/city_pickers#-changelog-tab-

城市数据已更新.
