### ISSUE TITLE
初始化child为空的Point时，会报错

### ISSUE THREAD

**Issue by addelete** [hanxu317317/city_pickers#5]
版本：0.1.8

重现：

````
Result result = await CityPickers.showCityPicker(
      height: 300,
      locationCode: '429021', // 湖北-神农架林区
      context: context,
    );
````

[https://github.com/hanxu317317/city_pickers/blob/master/lib/src/base/base.dart#L120](https://github.com/hanxu317317/city_pickers/blob/master/lib/src/base/base.dart#L120)
这一行，_city.child.first 会抛出一个错误，因为此时的_city.child可能为空List，我看到下面的代码你有验证isEmpty，这里不知道是不是疏忽了

**Comment by hanxu317317** [comment]
之前. 未考虑过. 会有某市级下. 区级为空的状态.  已经加入判断. 并修复了.
