### ISSUE TITLE
请问哪个版本是可以显示出数据的？

### ISSUE THREAD

**Issue by hanleiZoro** [hanxu317317/city_pickers#50]
最新的0.1.22是显示不出数据的！

**Comment by hanxu317317** [comment]
@hanleiZoro  什么叫做不显示数据呢?  亲~如果感觉可能有问题.建议拉下来这个项目. 本地跑一下. Example看一下.

**Comment by hanleiZoro** [comment]
<img width="1086" alt="屏幕快照 2019-08-12 下午2 27 12" src="https://user-images.githubusercontent.com/38712031/62848343-ce9b0080-bd0d-11e9-93e0-d4a7139c72ac.png">

*这个版本确实显示不出数据的，能请教下是什么问题么？*

*这是我的代码*

<img width="614" alt="屏幕快照 2019-08-12 下午2 33 54" src="https://user-images.githubusercontent.com/38712031/62848495-8c25f380-bd0e-11e9-8201-f5e161cc049e.png">

*执行效果是这样的*

![Simulator Screen Shot - iPhone Xʀ - 2019-08-12 at 14 31 31](https://user-images.githubusercontent.com/38712031/62848354-e3779400-bd0d-11e9-9a48-d97f46e2488c.png)

**Comment by hanxu317317** [comment]
@hanleiZoro 

![image](https://user-images.githubusercontent.com/8518989/62849594-d27d5180-bd12-11e9-9db7-1662004d05ca.png)
你可以试试:
showCityPicker(
....
                 itemExtent: 50,
                  itemBuilder: (item, list, index) {
                    return Center(
                        child: Text(item)
                  }
)
为Text(item) 赋值您需要的颜色. 怀疑是主题色. 导致字体与背景重复了

**Comment by hanleiZoro** [comment]
确实我下载demo测试的时候复现了这个问题。 导致我以为没有数据呢！ oh my god。 我断点调试了好久没有找到答案
