### ISSUE TITLE
可以设置确定和取消的高度吗，字体设置大了有文字只显示一半，谢谢您

### ISSUE THREAD

**Issue by Hemomoo** [hanxu317317/city_pickers#53]

**Comment by hanxu317317** [comment]
@Bright0206 之前设计的确没有考虑这点.  我下一个小版本加上.

![image](https://user-images.githubusercontent.com/8518989/63493495-56db8b80-c4ee-11e9-9693-c8a486a7a8d7.png)
是这样的bug吧?

**Comment by Hemomoo** [comment]
是的 谢谢您！!!! 幸苦了

**Comment by hanxu317317** [comment]
@Bright0206 代码已合并 并已经更新到 0.1.25,  修复此问题
