### ISSUE TITLE
打包apk时报错

### ISSUE THREAD

**Issue by zinkLin** [hanxu317317/city_pickers#54]
您好，我在运行flutter build apk时，报了如下错误

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':city_pickers'.
> Failed to find Platform SDK with path: platforms;android-27

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Please review your Gradle project setup in the android/ folder.

**Comment by hanxu317317** [comment]
@zinkLin 貌似是grandle配置的问题.

**Comment by hanxu317317** [comment]
参考一下: https://github.com/flutter/flutter/issues/23777
