### ISSUE TITLE
怎么在城市选择器（CityPickers.showCitiesSelector）的上面加一栏，显示选择过的城市、热门城市？？

### ISSUE THREAD

**Issue by topjx** [hanxu317317/city_pickers#55]
这不是插件的error，只是我这边需要实现的一个需求。。。
<img width="402" alt="屏幕快照 2019-08-26 下午4 38 20" src="https://user-images.githubusercontent.com/13688627/63677615-f1eea100-c81f-11e9-95f5-63b00c39a8ea.png">

**Comment by hanxu317317** [comment]
在原有基础增加热门? @topjx

**Comment by topjx** [comment]
是啊 现在有这么个需求 @hanxu317317

**Comment by hanxu317317** [comment]
@topjx 大概1周左右后. 我把这个功能加上. 这个功能之前我本地写过. 一直没po出来

**Comment by topjx** [comment]
ok

**Comment by hanxu317317** [comment]
先打开. 解决后. 再关闭

**Comment by hanxu317317** [comment]
@topjx 觉得这种的怎么样?
![image](https://user-images.githubusercontent.com/8518989/64336342-49a2be80-d00f-11e9-8efa-986d8446223a.png)

**Comment by topjx** [comment]
@hanxu317317  可以 牛啤

**Comment by hanxu317317** [comment]
@topjx 代码已合并 并已经更新到 0.1.25
