### ISSUE TITLE
有没有提供  给一个areaId  返回具体的中文地址的方法

### ISSUE THREAD

**Issue by desire0420** [hanxu317317/city_pickers#62]
有没有提供  给一个areaId  返回具体的中文地址的方法呀，后台返回的不是中文，而是最后选择的id

**Comment by hanxu317317** [comment]
这个方法, 10.1前我会暴露出来. 现在最没办法的方式. 只能自己去遍历citiesdata. 然后.....
@wang709693972wei

**Comment by desire0420** [comment]
坐等发布新版本

**Comment by hanxu317317** [comment]
@wang709693972wei 哈哈好的~~最近业务压力大. 这个功能就搁置了.

**Comment by desire0420** [comment]
想问下  您把市和县 的后面两级数据  放在同一个map里面，那样我遍历市的时候 也要对县的数据遍历。遍历的数据会有点多，楼主有没考虑把市和区的数据分开。

**Comment by hanxu317317** [comment]
@wang709693972wei 这个问题考虑过,主要是以下几点

- 方便数据递归, 不需要指定是某级数据, 找到就返回, 方便用户使用 ```getLocaionInfo(code)```
- 数据结构定义抽象, 如果有四级数据, 直接追加. 不需要更改太多的代码.
- 以上都是我现编的. 这个数据结构是参考现有项目, 直接用的, 没过脑子. 不过上边第2条还是有用的.

**Comment by hanxu317317** [comment]
fixed:  0.1.26
![image](https://user-images.githubusercontent.com/8518989/65677715-b0524f80-e084-11e9-8973-1464c85f001d.png)

**Comment by wang709693972wei** [comment]
请问下 只有两个数据的时候   能否让滚轮UI 均分空间，  现在是左对齐  界面看起来不太好看。


------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 下午5:40
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 有没有提供  给一个areaId  返回具体的中文地址的方法 (#62)




fixed:  0.1.26

**Comment by desire0420** [comment]
升级了版本，试了你暴露的方法  还是取不到信息哦。具体提了新的issues
