### ISSUE TITLE
根据Area 拿不到具体的位置信息

### ISSUE THREAD

**Issue by desire0420** [hanxu317317/city_pickers#65]
我是自己定义的数据 ，滚轮能正常显示，但是AreaID 拿地址信息为null  调式了  代码，确实没有返回数据

![image](https://user-images.githubusercontent.com/12178442/65735655-be4ab380-e10a-11e9-9406-9f17273c25ae.png)

**Comment by desire0420** [comment]
![image](https://user-images.githubusercontent.com/12178442/65735597-8c395180-e10a-11e9-9893-0d00f092d6e0.png)

**Comment by hanxu317317** [comment]
你如果是自定义数据的话. 需要先声明你的数据.
```
class CityPickers {
  /// static original city data for this plugin
  static Map<String, dynamic> metaCities = meta.citiesData;

  /// static original province data for this plugin
  static Map<String, dynamic> metaProvinces = meta.provincesData;

  static utils(
      {Map<String, dynamic> provinceData, Map<String, dynamic> citiesData}) {
    print("CityPickers.metaProvinces::: ${CityPickers.metaCities}");
    return CityPickerUtil(
      provincesData: provinceData ?? CityPickers.metaProvinces,
      citiesData: citiesData ?? CityPickers.metaCities,
    );
  }
}
```
你可以
```
CityPickers.metaCities = xxx;
CityPickers.metaProvinces = yyy;
 CityPickerUtil cityPickerUtils = CityPickers.utils();
```

**Comment by desire0420** [comment]
因为我是用的本地数据，我自定义了数据。后台服务器需要的code  和你的数据不一致，我修改了。
选择地址都可以使用，但是根据code 拿具体地址，返回数据为null
------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 上午10:32
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)




1010165 是一个什么地址???
 http://www.syx7.com/Citydm.asp?Field=Areadm&keyword=10101065
 
建议去查一下...数据的准确性.

**Comment by hanxu317317** [comment]
```
1. 
CityPickers.metaCities = 你的城市数据;
CityPickers.metaProvinces = 你的省份数据;
CityPickerUtil cityPickerUtils = CityPickers.utils();

2. 
CityPickerUtil cityPickerUtils = CityPickers.utils(provinceData: 你的城市数据, ,citiesData: 你的城市数据);
```

**Comment by desire0420** [comment]
目前发现 还存在两个问题，


1，不自定义数据的话，通过
CityPickerUtil cityPickerUtils = CityPickers.utils();cityPickerUtils.getAreaResultByCode('421023')这样得到的数据是 {"provinceName":"湖北省","provinceId":"420000","cityName":"监利县","cityId":"421023"}没有得到市 ， 正确的结果应该是  湖北省荆州市监利县
2.自定义数据CityPickers.metaCities = 你的城市数据; CityPickers.metaProvinces = 你的省份数据;CityPickerUtil cityPickerUtils = CityPickers.utils();cityPickerUtils.getAreaResultByCode('10101065')这样获取中文位置，必须要等位置选择之后，因为哦我是使用的type1   也就是说要等底部滚轮弹出后再去格式化  才有地址数据，在滚轮弹出之前去格式化 没有返回数据，感觉是哪里初始化的问题。



------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 上午10:36
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)



CityPickers.metaCities = 你的城市数据; CityPickers.metaProvinces = 你的省份数据; CityPickerUtil cityPickerUtils = CityPickers.utils();

**Comment by hanxu317317** [comment]
421023 的数据索引, 只能检索到city一级. 无法再向下深入了啊.

**Comment by hanxu317317** [comment]
typ1中有返回结果 .不需要你再次通过手动去获取地区信息啊

> Result 对象中. 包含了所有的信息

![image](https://user-images.githubusercontent.com/8518989/65739391-aaf21500-e117-11e9-998d-69ab0c8871fe.png)

**Comment by desire0420** [comment]
现在根据10115025拿到是这样的数据 
{"provinceName":"湖北","provinceId":"10115000","cityName":"监利","cityId":"10115025"}




但是我在弹框选择地址后  点击确定  给的resule  是这样的
{"provinceName":"湖北","provinceId":"10115000","cityName":"荆州","cityId":"10115010","areaName":"监利","areaId":"10115025"}







------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:10
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)




421023 的数据索引, 只能检索到city一级. 无法再向下深入了啊.

**Comment by hanxu317317** [comment]
我的邮箱是 sanfan.hx@alibaba-inc.com  方便将您的自定义的省市数据传给我么? 我本地看一下是哪里的问题.

**Comment by desire0420** [comment]
楼主，你好 看来下源码 你的这个地方写错了
应该是areaName   和areaID  
能不能修复下  发个版本呀，等着用，谢谢
------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:18
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)




我的邮箱是 sanfan.hx@alibaba-inc.com  方便将您的自定义的省市数据传给我么? 我本地看一下是哪里的问题.

**Comment by hanxu317317** [comment]
小哥. 你说的这个地方是哪里? 邮件回来的. 没有看到?
![image](https://user-images.githubusercontent.com/8518989/65740981-31f5bc00-e11d-11e9-9c99-ee022de001b1.png)

**Comment by desire0420** [comment]
------------------ 原始邮件 ------------------
发件人: "hanxu317317"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:51
收件人: "hanxu317317/city_pickers"<city_pickers@noreply.github.com>;
抄送: "design"<709693972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)




小哥. 你说的这个地方是哪里? 邮件回来的. 没有看到?

**Comment by hanxu317317** [comment]
```
   if (cityPoint != null && !cityPoint.isNull) {
      locationInfo.cityName = cityPoint.name;
      locationInfo.cityId = cityPoint.code.toString();
    }

    if (areaPoint != null && !areaPoint.isNull) {
      locationInfo.cityName = areaPoint.name;
      locationInfo.cityId = areaPoint.code.toString();
    }
小哥说 的这里吧?  这个版本发的太急了. 没好好测试这块.
```

**Comment by desire0420** [comment]
是的，就是最后那个位置，改成area属性就好了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hanxu317317 <notifications@github.com&gt;
发送时间: 2019年9月27日 11:55
收件人: hanxu317317/city_pickers <city_pickers@noreply.github.com&gt;
抄送: 王伟 <709693972@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)



   if (cityPoint != null &amp;&amp; !cityPoint.isNull) {       locationInfo.cityName = cityPoint.name;       locationInfo.cityId = cityPoint.code.toString();     }     if (areaPoint != null &amp;&amp; !areaPoint.isNull) {       locationInfo.cityName = areaPoint.name;       locationInfo.cityId = areaPoint.code.toString();     } 小哥说 的这里吧?  这个版本发的太急了. 没好好测试这块.

**Comment by hanxu317317** [comment]
ok  我现在处理一下. 并发一个小版本

**Comment by desire0420** [comment]
楼主可以提供滚轮，选择之后字体颜色这个功能么，

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hanxu317317 <notifications@github.com&gt;
发送时间: 2019年9月27日 11:57
收件人: hanxu317317/city_pickers <city_pickers@noreply.github.com&gt;
抄送: 王伟 <709693972@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)




ok  我现在处理一下. 并发一个小版本

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/65741416-8fd6d380-e11e-11e9-9d66-ddb521901462.png)

选中后的颜色么?

**Comment by desire0420** [comment]
是的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hanxu317317 <notifications@github.com&gt;
发送时间: 2019年9月27日 12:01
收件人: hanxu317317/city_pickers <city_pickers@noreply.github.com&gt;
抄送: 王伟 <709693972@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hanxu317317/city_pickers] 根据Area 拿不到具体的位置信息 (#65)





 
选中后的颜色么?

**Comment by hanxu317317** [comment]
已解决提出的bug:  0.1.27

选中加颜色的. 我看一下. 需要怎么实现.
