### ISSUE TITLE
点击取消按钮，报错

### ISSUE THREAD

**Issue by vitalityzhang** [hanxu317317/city_pickers#67]
![CleanShot 2019-10-11 at 20 57 28](https://user-images.githubusercontent.com/17313851/66693114-ef64df80-ecd7-11e9-9ecc-ece923af3794.png)

`
_addressClick() async {
    _temp = await CityPickers.showCityPicker(
      barrierDismissible: false,
      theme: ThemeData(
        primarySwatch: buttonColor,
      ),
      context: context,
      height: 200,
    );

    setState(() {
      _address = "${_temp.provinceName}${_temp.cityName}${_temp.areaName}";
    });
  }
`

**Comment by hanxu317317** [comment]
你点击取消的时候. _temp还是udnefined. 怎么去取provinceName.
