### ISSUE TITLE
多个地方使用时选择内容为第一次打开的那个内容

### ISSUE THREAD

**Issue by LvJson** [hanxu317317/city_pickers#68]
具体：我有A、B两个Tab页面，而且他们都需要这个选择器，但是选择内容却不同。当我在A页面打开这个选择器后，再在B页面打开就会出现选择内容和A是一样的，这是个奇怪的现象。当我把选择内容前面的code更改后就没问题了，但我觉得这样好像不是很合理，希望大佬关注下！

**Comment by hanxu317317** [comment]
@LvJson  在a与b不同tab中, 设定的省份与城市的数据不是同一份. 但是先打开A后. 在B中打开的依然是A中的选择器么?

**Comment by LvJson** [comment]
是的，就是这样

**Comment by LvJson** [comment]
tab A的数据：
` Map<String, String> provincesData = {
    "10000": "绍兴市",
  };
  Map<String, dynamic> citiesData = {
    "10000": {
      "11000": {"name": "袍江局"}
    },
    "11000": {
      "11100": {"name": "城沿小区"},
    }
  };`

tab B的数据：
`Map<String, String> provincesData = {
    "10000": "绍兴市",
  };
  Map<String, dynamic> citiesData = {
    "10000": {
      "11000": {"name": "袍江局"},
      "12000": {"name": "嵊州局"},
    }
  };`

**Comment by hanxu317317** [comment]
@LvJson 查看了一下. 的确有这样的问题. 我会尽快处理这个BUG

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/67471347-d23df280-f681-11e9-8f2c-66f40a71a391.png)

定位到了问题的所在.  当初为了优化性能, 将每次构建三级树的结果缓存. 由于我们的城市数据key未变化. 所以每次都拿到了第一次初始化的结果.

**Comment by LvJson** [comment]
谢谢

**Comment by hanxu317317** [comment]
version: 0.1.28

https://pub.dev/packages/city_pickers

**Comment by LvJson** [comment]
好的，多谢！！！

**Comment by hanxu317317** [comment]
不知道我这个解决方案是不是能解决你的问题. 我是在一个TAB中做了二个按钮. 如果能解决您的问题. 请回复结果.

**Comment by LvJson** [comment]
解决了我的问题！
