### ISSUE TITLE
安卓的compileSdkVersion 27 需要升级 compileSdkVersion 28

### ISSUE THREAD

**Issue by godgege** [hanxu317317/city_pickers#71]
Flutter version 1.11.0 不适应这个版本

**Comment by hanxu317317** [comment]
好的.收到. 我会升级.

**Comment by hanxu317317** [comment]
@ismanong 已经在build中把版本号27 => 28. 并已经发布到 [0.1.29](https://pub.dev/packages/city_pickers/versions)

**Comment by godgege** [comment]
谢谢你

**Comment by hanxu317317** [comment]
@ismanong 这个问题, 已经得到了解决么? 因为我另一个 issue中有人反馈这个问题.

**Comment by godgege** [comment]
我之前是直接拉取的你修改后的git代码。因为之前pub获取可能有点延迟或者别的问题。但是直接引入你的git包就好了，刚刚测了city_pickers: ^0.1.30 这个版本，是可以的，圣诞快乐。
