### ISSUE TITLE
打包资源文件出错

### ISSUE THREAD

**Issue by deboLing** [hanxu317317/city_pickers#75]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':compressimage:verifyReleaseResources'.      
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/jishukaifa/svn/Buybit_flutter_coin_trade/buybit_app/build/compressimage/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/jishukaifa/svn/Buybit_flutter_coin_trade/buybit_app/build/compressimage/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     

升级到最新版，flutter  SDK版本是1.12

**Comment by JerryJian** [comment]
Same issue after upgrade flutter sdk to 1.12

**Comment by vitalityzhang** [comment]
https://stackoverflow.com/questions/54791193/java-util-concurrent-executionexception-com-android-builder-internal-aapt-v2-aa

Hope it helps

**Comment by JerryJian** [comment]
I rollback flutter version to v1.9.1+hotfix.6, the problem disappeared.
command: flutter version v1.9.1+hotfix.6

**Comment by aboutmydreams** [comment]
same problem

build apk success after delete the packege. 

## the log：
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processReleaseResources'.               
> Android resource linking failed                                       
  Output:  /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /Users/dengwenhao/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/067c550bab45744a730d55ac6d07bb79/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/dengwenhao/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\                                                   
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/armeabi-v7a/AndroidManifest.xml\
          -o\                                                           
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/processed_res/release/processReleaseResources/out/resources-armeabi-v7aRelease.ap_\
          -R\                                                           
          @/Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/incremental/processReleaseResources/resources-list-for-resources-armeabi-v7aRelease.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --proguard\                                                   
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/proguard-rules/release/aapt_rules.txt\
          --custom-package\                                             
          com.example.citypickersexample\                               
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/symbols/release/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
  Output:  /Users/dengwenhao/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/d1e31fc57430ff614027e4e63f629ecb/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
  /Users/dengwenhao/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/d1e31fc57430ff614027e4e63f629ecb/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
  error: failed linking references.                                     
  Command: /Users/dengwenhao/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/067c550bab45744a730d55ac6d07bb79/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/dengwenhao/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\                                                   
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/armeabi-v7a/AndroidManifest.xml\
          -o\                                                           
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/processed_res/release/processReleaseResources/out/resources-armeabi-v7aRelease.ap_\
          -R\                                                           
          @/Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/incremental/processReleaseResources/resources-list-for-resources-armeabi-v7aRelease.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --proguard\                                                   
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/proguard-rules/release/aapt_rules.txt\
          --custom-package\                                             
          com.example.citypickersexample\                               
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /Users/dengwenhao/coding/learn/city_pickers/example/build/app/intermediates/symbols/release/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 35s

**Comment by pzgz** [comment]
Use latest codes from the repo will fix this issue temporary:

```yaml
  city_pickers: 
    git: 
      url: https://github.com/hanxu317317/city_pickers.git

```

**Comment by rmbgold** [comment]
将compileSdkVersion改为28,作者十几天前就更新了，用git代码没问题，希望插件尽快更新到pub库哈。

**Comment by hanxu317317** [comment]
0.1.29 已经发布到线上了.  亲~~~

**Comment by hanxu317317** [comment]
> @ismanong 已经在build中把版本号27 => 28. 并已经发布到 0.1.29

**Comment by w4mxl** [comment]
@hanxu317317 @pzgz 
我这边使用最新的 0.1.29 打包时，还是会报同样的错误哦。
请问 0.1.29 是不是没有修复掉这个 bug ？

**Comment by hanxu317317** [comment]
@w4mxl 看了一下文档. 应该还是版本没统一. 我周末会处理一下这个问题.

如果可以. 您可以借鉴: https://www.jianshu.com/p/6729bca200ea

看看能不能先解决这个问题.

**Comment by w4mxl** [comment]
@hanxu317317 好的，辛苦了。目前我是临时通过把

`city_pickers: ^0.1.29`

改成：

```
city_pickers: 
    git: 
      url: https://github.com/hanxu317317/city_pickers.git
```

这样倒是可以正常打包的。我猜测pub上的 0.1.29 并非是最新的 git 代码

**Comment by ber6789** [comment]
我这边用了 git仓库的，依然不行，而且还有新的报错
```
city_pickers: 
    git: 
      url: https://github.com/hanxu317317/city_pickers.git
```

**The SDK directory 'D:\flutter\.pub-cache\git\city_pickers-e756c84532883a6066cc56d3108a7fdcbd823636\android\Users\ontwo\Library\Android\sdk' does not exist.**

上面就是新的报错

**Comment by hanxu317317** [comment]
@ber6789 好像把我自己的环境变量传上去了. 我去干掉他.

**Comment by hanxu317317** [comment]
@ber6789 亲可以试一下. 是否解决.

**Comment by hanxu317317** [comment]
已经更新最新的版本号: 0.1.30, 亲可以测试一下. 我这边本地是可以打包了.@deboling @JerryJian @JerryJian @ber6789 @w4mxl

**Comment by w4mxl** [comment]
> 已经更新最新的版本号: 0.1.30, 亲可以测试一下. 我这边本地是可以打包了.@deboLing @JerryJian @JerryJian @ber6789 @w4mxl

我这边测试了下 `city_pickers: ^0.1.30` ，打包没问题了～
谢谢修复

**Comment by JerryJian** [comment]
谢谢修复，最近APP要发布，暂时没有更新，非常感谢 @hanxu317317
