### ISSUE TITLE
Module 'city_pickers' not found iOS无法打包

### ISSUE THREAD

**Issue by yangyu92** [hanxu317317/city_pickers#80]
Building AOT snapshot in release mode (ios-release)...          
Building App.framework for arm64...

Building App.framework for armv7...
Building AOT snapshot in release mode (ios-release)...             71.4s
Built to build/aot/.
warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
warning: line table parameters mismatch. Cannot emit.

**Comment by zhuxiwen** [comment]
最后怎么好的，我也遇到这个问题了0.0?!@ @yangyu92

**Comment by zhuxiwen** [comment]
不是该插件的原因，我flutter build ios 后又能flutter run了-.-
