### ISSUE TITLE
能移除插件，改为纯dart项目吗

### ISSUE THREAD

**Issue by mjl0602** [hanxu317317/city_pickers#82]
我看这个iOS和安卓都没写代码，如果弄成纯dart包，就不会因为一些IDE的配置冲突而报错。

**Comment by hanxu317317** [comment]
纯dart包. 只能做工具类方法. android&ios是一定要有的.

**Comment by mjl0602** [comment]
只是纯dart工具的话，带插件包不利于以后维护，所以没用到原生代码的情况下，最好是去掉插件包部分。也可以避免冲突。

我记得我提这个issue的时候还去确认了，你没有用到原生代码。

**Comment by hanxu317317** [comment]
好的. 这个是我们在flutter早期的时候接入的文档各种都没有. 摸索着创建的项目.   看来需要整理一下了.

**Comment by mjl0602** [comment]
你直接创建新插件再把dart代码都拉过去就行了，带原生平台代码会造成一堆问题。

我也在维护带有原生项目的插件包，flutter日常大改，还有一堆跑不起来的issue……我维护的纯dart项目，基本就没什么问题。
