### ISSUE TITLE
选择香港地区后再次点击就出现报错

### ISSUE THREAD

**Issue by hzp1993** [hanxu317317/city_pickers#84]
I/flutter ( 9938): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9938): The following NoSuchMethodError was thrown building InheritRouteWidget:
I/flutter ( 9938): The getter 'child' was called on null.
I/flutter ( 9938): Receiver: null
I/flutter ( 9938): Tried calling: child
I/flutter ( 9938): 
I/flutter ( 9938): The relevant error-causing widget was:
I/flutter ( 9938):   InheritRouteWidget
I/flutter ( 9938):   file:///Users/hezhipeng/app/flutter/.pub-cache/hosted/pub.flutter-io.cn/city_pickers-0.1.30/lib/src/mod/picker_popup_route.dart:54:16
I/flutter ( 9938): 
I/flutter ( 9938): When the exception was thrown, this was the stack:
I/flutter ( 9938): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 9938): #1      _BaseView._initController (package:city_pickers/src/base/base.dart:120:33)
I/flutter ( 9938): #2      _BaseView.initState (package:city_pickers/src/base/base.dart:96:5)
I/flutter ( 9938): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
I/flutter ( 9938): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 9938): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 9938): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #70     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 9938): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 9938): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 9938): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 9938): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 9938): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 9938): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #118    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 9938): #119    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 9938): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 9938): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 9938): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 9938): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 9938): #129    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
I/flutter ( 9938): #130    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter ( 9938): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #132    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:605:16)
I/flutter ( 9938): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter ( 9938): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter ( 9938): #141    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter ( 9938): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter ( 9938): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter ( 9938): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter ( 9938): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter ( 9938): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #155    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter ( 9938): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter ( 9938): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 9938): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9938): #159    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter ( 9938): #160    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter ( 9938): #161    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 9938): #162    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter ( 9938): #163    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter ( 9938): #164    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter ( 9938): #168    _invoke (dart:ui/hooks.dart:259:10)
I/flutter ( 9938): #169    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter ( 9938): (elided 3 frames from package dart:async)
I/flutter ( 9938): 
I/flutter ( 9938): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by hanxu317317** [comment]
这个问题. 现在还有么?

**Comment by hanxu317317** [comment]
最新1.0.1 中已经修复发布, 并且解决unsafe的问题.
