### ISSUE TITLE
 fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by zinwalin** [hanxu317317/city_pickers#90]
Xcode's output:
↳
    In file included from /Users/michael/Development/city_pickers/ios/Classes/CityPickersPlugin.m:1:
    /Users/michael/Development/city_pickers/ios/Classes/CityPickersPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    /Users/michael/Development/city_pickers/ios/Classes/CityPickersPlugin.h:1:9: note: did not find header 'Flutter.h' in framework 'Flutter' (loaded from
    '/Users/michael/Development/zc_sports/ios/Pods/../Flutter')
    1 error generated.

Encountered error while building for device.

**Comment by hanxu317317** [comment]
重新试一下最近版. flutter版本更新的比较快.
