### ISSUE TITLE
获取省-市-区 点击事件和当前值如何获取？

### ISSUE THREAD

**Issue by zhuyonghao134123** [hanxu317317/city_pickers#91]
1.自定义数据
2.动态更新自定义数据，比如选择北京，我要动态改变北京下边的市和区
3.所以我这边如何获取三级联动中当前的值是什么

**Comment by hanxu317317** [comment]
把自定义的数据预先做成json.  按照对应的格式就可以了.  关于如何获取. 就是自动返回的数据.
