### ISSUE TITLE
请问如何像截图这样支持只选择省或选择省市或选择省市县呢

### ISSUE THREAD

**Issue by JJH0901** [hanxu317317/city_pickers#94]
![image](https://user-images.githubusercontent.com/19657983/80309490-faacd200-8807-11ea-8f85-6cfcbbaedd14.png)

**Comment by JJH0901** [comment]
是否可以增增加请选择这个选项呢

**Comment by hanxu317317** [comment]
![image](https://user-images.githubusercontent.com/8518989/92469976-52246b00-f208-11ea-8d08-03ae005a3baf.png)
![image](https://user-images.githubusercontent.com/8518989/92469992-55b7f200-f208-11ea-910e-3295e6227f41.png)

如图
